### ISSUE TITLE
Rules' AND operator with empty rules always intercept the request

### ISSUE THREAD

**Issue by 255kb** [mockoon/commons-server#6]
**Describe the bug**
Having empty rules with "AND" operator serves the corresponding response even if another response's rules match

**To Reproduce**
- create 2 responses
- set the first response's rules to AND, and remove all rules
- add one rule on the second one
- make a call that matches the second response, you get the first one

[bug#6.zip](https://github.com/mockoon/commons-server/files/6392096/bug.6.zip)

**Expected behavior**
We should get the second one

**Mockoon version:**
all

**OS / OS version:**
all

**Comment by mauriceackel** [comment]
The error is this [line](https://github.com/mockoon/commons-server/blob/32f0f3fe723415cf12fba82fd69430ba1d301085/src/libs/response-rules-interpreter.ts#L42)

The problem is that `Array.every` returns `true` if the input array is empty.
Potential fix:
```javascript
let response = this.routeResponses.find((routeResponse) => {
  if (routeResponse.rules.length === 0) {
    return false;
  }

  return routeResponse.rulesOperator === 'AND'
    ? routeResponse.rules.every(this.isValidRule)
    : routeResponse.rules.some(this.isValidRule)
});
```

Notice, that I also changed `!!routeResponse.rules.find(this.isValidRule)` to `routeResponse.rules.some(this.isValidRule)` and removed the unnecessary double negation at `routeResponse.rules.every(this.isValidRule)`

**Comment by 255kb** [comment]
Thanks @mauriceackel your fix is indeed working!
