### ISSUE TITLE
Add baseUrl variable to templating RequestHelpers

### ISSUE THREAD

**Issue by louiealmeda** [mockoon/commons-server#7]
**Is your feature request related to a problem? Please describe.**

I wanted to return an absolute path on a response, ideally it starts with the baseUrl where my current mockAPI is served on. The sample request response looks like this:

`GET: http://localhost:3001/api/users/123`
```
{
    "id": "123"
    "name": "Foobar",
    "imageUrl": "http://localhost:3001/api/images/123"
}
```
Currently, there's no way to achieve this.

**Describe the solution you'd like**

Adding a `baseUrl` will enable us to do this:

`GET: /users/:userId`

```
{
    "id": "{{urlParam 'userId'}}"
    "name": "Foobar",
    "imageUrl": "{{baseUrl}}/images/{{urlParam 'userId'}}"
}
```

**Describe alternatives you've considered**
Tried using hostname etc.. 

**Additional context**
Discussion here: https://github.com/mockoon/mockoon/discussions/466

**Comment by louiealmeda** [comment]
Hi @255kb, I would like to work on this if possible. It's going to be my very first open source contribution though, so you might need to bear with me a little :)

**Comment by 255kb** [comment]
Sure I assigned it to you 😃 
To guide you a little bit, what needs to be done:
- Add a new helper function [there](https://github.com/mockoon/commons-server/blob/main/src/libs/templating-helpers/request-helpers.ts). You only have access to the [current request](https://github.com/mockoon/commons-server/blob/main/src/libs/templating-helpers/request-helpers.ts#L5), so instead of extracting the host, port and prefix, it may be easier to pass the `Environment` to the [`TemplateParser` function](https://github.com/mockoon/commons-server/blob/main/src/libs/templating-helpers/request-helpers.ts#L5) when it's called (like [here](https://github.com/mockoon/commons-server/blob/main/src/libs/server.ts#L327))
- Add the corresponding test cases, like for the [`queryParam` helper](https://github.com/mockoon/commons-server/blob/main/test/template-parser.spec.ts#L517). (not everything is covered yet, so you may not find examples for all the helpers)

And I will take care of preparing the docs for the next release after you finish.
Feel free to ask if you have any question. You can also join our [Discord server](https://discord.com/invite/JmTBk59MTb) if you want to discuss or need any help.

**Comment by louiealmeda** [comment]
Thanks for the guide @255kb, that's extremely helpful. I'm working on it 🙂
